### ISSUE TITLE
Stream doesn't runing??

### ISSUE THREAD

**Issue by patrickano** [saiunes/streamSaiUnes#1]
i'm doing the process step by step with no result😕
![Uploading لقطة الشاشة 2023-02-16 172731.jpg…]()

**Comment by saiunes** [comment]
The attached screenshot is not working!! 
in addition, we've just released a new version v2.13, consider updating
and follow the steps on the video from the radio channel business:
https://saiunes.com/make-100k-from-radio-channel-business-and-a-solid-passive-income-stratigy/
