### ISSUE TITLE
command issue

### ISSUE THREAD

**Issue by patrickano** [saiunes/streamSaiUnes#2]
when i tape this command ./streamSaiUnes
the terminal told me that this isn't a file or directory

![لقطة الشاشة 2023-02-18 134322](https://user-images.githubusercontent.com/108905853/219866474-daf11f8e-d89f-4d93-a725-4612b5f7ec20.jpg)

**Comment by saiunes** [comment]
try typing "ls" to list all the files and folders in your current dir!! it seems that ur in the wrong directory!
also check that ur using UBUNTU 22.04LTS otherwise the tool will not work

**Comment by patrickano** [comment]
Thank you🙏🏻
