### ISSUE TITLE
facebook live not working

### ISSUE THREAD

**Issue by Django06** [saiunes/streamSaiUnes#3]
Hello, 
thanks for sharing.
I've tested the tool today in Facebook live, I've copied the stream key from Facebook and I flowed the explanation.
the tool gives me that Facebook live is connected but when I go to Facebook I found that the stream is not started.

version: v2.13

<img width="790" alt="Screenshot 2023-02-19 at 01 09 24" src="https://user-images.githubusercontent.com/44341257/219905101-222aca71-a0a8-43db-91f5-7b90e61ed3dc.png">

older version:
<img width="721" alt="Screenshot 2023-02-19 at 00 44 54" src="https://user-images.githubusercontent.com/44341257/219904481-97be36a5-cac1-451b-b812-256964e38ef8.png">

**Comment by saiunes** [comment]
just tested it and it's working fine!
make sure to rename the video file to 1.mp4 or something simpler

**Comment by patrickano** [comment]
hi @Django06 
follow those steps one by one oky

wget https://github.com/saiunes/streamSaiUnes/releases/download/v1.0/install
chmod 777 install
./install
cd streamSaiUnes
chmod 777 streamSaiUnes

ls

cd video

wget (video link)

ls

cd ..

ls

tmux

then choose the platforme that you want to stream on it

good luck

**Comment by Django06** [comment]
@saiunes  @patrickano **thanks for replaying** 👍 👍  . 
I followed all the steps one by one, as you can see in those images :
<img width="608" alt="Screenshot 2023-02-20 at 01 18 03" src="https://user-images.githubusercontent.com/44341257/219984501-d4be2fdb-b21f-43eb-a7df-ffd8bae75582.png">
<img width="744" alt="Screenshot 2023-02-20 at 01 19 46" src="https://user-images.githubusercontent.com/44341257/219984509-d69666a0-e4e9-4908-9b5d-5976c9a98077.png">

and the stream on Facebook is not starting, maybe I'm doing something wrong on Facebook.
I'm using a Facebook page that I create yesterday. page with 0 followers.

**Comment by Django06** [comment]
I test it on youtube and I had the same problem and also i tried to change the video name and change the video it self.
nothing works

**Comment by saiunes** [comment]
Problem solve, kindly update to the latest version! 
if you have other issues, consider posting your issue in the coaching section on SaiUnes community and ill install it for you.
