### ISSUE TITLE
I can't install the tool

### ISSUE THREAD

**Issue by simol11** [saiunes/streamSaiUnes#4]
When I past the code in my droplet console

get https://github.com/saiunes/streamSaiUnes/releases/download/v2.13/install
chmod 777 install
./install
cd streamSaiUnes
chmod 777 streamSaiUnes

it shows up 
HTTP request sent, awaiting response... 404 Not Found

How can I solve that ?
![Screenshot from 2023-02-19 20-59-45](https://user-images.githubusercontent.com/125764294/219972220-554e3289-15f0-4b69-bcf7-aa2209c788ac.png)

**Comment by saiunes** [comment]
Problem solve, kindly update to the latest version! 
if you have other issues, consider posting your issue in the coaching section on SaiUnes community and ill install it for you.
