### ISSUE TITLE
I can't run the streamSaiUnes app

### ISSUE THREAD

**Issue by issam126** [saiunes/streamSaiUnes#5]
when I run the streamSaiUnes app it give me this error:
-bash: ./streamSaiUnes: No such file or directory

**Comment by ILYAS97ss** [comment]
same error any solution

**Comment by ILYAS97ss** [comment]
hi i found the solution try creating new droplet and then flow this steps 

wget https://github.com/saiunes/streamSaiUnes/releases/download/v1.0/install
chmod 777 install
./install
cd streamSaiUnes
chmod 777 streamSaiUnes

ls

cd video

wget (video link)

ls

cd ..ls


ls

tmux

./streamSaiUnes

then choose the platforme that you want to stream on it

good luck


![cv](https://user-images.githubusercontent.com/123819872/220185128-32f51033-920d-4fa5-b166-31f06e7b67c0.PNG)

the error that i have had now is that when i close the tmux command the stream becames like this any solotion guys

**Comment by issam126** [comment]
thanks

**Comment by simol11** [comment]
> hi i found the solution try creating new droplet and then flow this steps
> 
> wget https://github.com/saiunes/streamSaiUnes/releases/download/v1.0/install chmod 777 install ./install cd streamSaiUnes chmod 777 streamSaiUnes
> 
> ls
> 
> cd video
> 
> wget (video link)
> 
> ls
> 
> cd ..ls
> 
> ls
> 
> tmux
> 
> ./streamSaiUnes
> 
> then choose the platforme that you want to stream on it
> 
> good luck
> 
> ![cv](https://user-images.githubusercontent.com/123819872/220185128-32f51033-920d-4fa5-b166-31f06e7b67c0.PNG)
> 
> the error that i have had now is that when i close the tmux command the stream becames like this any solotion guys

Hey bro, how did you fix the second problem related to closing the tmux?

**Comment by ILYAS97ss** [comment]
> > hi i found the solution try creating new droplet and then flow this steps
> > wget https://github.com/saiunes/streamSaiUnes/releases/download/v1.0/install chmod 777 install ./install cd streamSaiUnes chmod 777 streamSaiUnes
> > ls
> > cd video
> > wget (video link)
> > ls
> > cd ..ls
> > ls
> > tmux
> > ./streamSaiUnes
> > then choose the platforme that you want to stream on it
> > good luck
> > ![cv](https://user-images.githubusercontent.com/123819872/220185128-32f51033-920d-4fa5-b166-31f06e7b67c0.PNG)
> > the error that i have had now is that when i close the tmux command the stream becames like this any solotion guys
> 
> Hey bro, how did you fix the second problem related to closing the tmux?

hi so do not use the commande cntrl+b and x   do not use it just close the root window it worked for me hope it works for u

**Comment by simol11** [comment]
thanks a lot

**Comment by saiunes** [comment]
Problem solve, kindly update to the latest version! 
if you have other issues, consider posting your issue in the coaching section on SaiUnes community and ill install it for you.
