### ISSUE TITLE
I can't install this version v2.13

### ISSUE THREAD

**Issue by issam126** [saiunes/streamSaiUnes#6]
I can't install this version v2.13
it give me this error:
TTP request sent, awaiting response... 404 Not Found
2023-02-20 18:56:30 ERROR 404: Not Found.
![Screen Shot 2023-02-20 at 19 56 35](https://user-images.githubusercontent.com/25804911/220181937-ef07861a-400c-4c1b-b5a2-db9298900367.png)

**Comment by saiunes** [comment]
Problem solve, kindly update to the latest version! 
if you have other issues, consider posting your issue in the coaching section on SaiUnes community and ill install it for you.
